  version: '2'
  services:
    accounts:
      image: networknt/com.networknt.ob.accounts-3.1.2:latest
      volumes:
        - ./accounts:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    balances:
      image: networknt/com.networknt.ob.balances-3.1.2:latest
      volumes:
        - ./balances:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    beneficiaries:
      image: networknt/com.networknt.ob.beneficiaries-3.1.2:latest
      volumes:
        - ./beneficiaries:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    direct-debits:
      image: networknt/com.networknt.ob.directdebits-3.1.2:latest
      volumes:
        - ./direct-debits:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    offers:
      image: networknt/com.networknt.ob.offers-3.1.2:latest
      volumes:
        - ./offers:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    parties:
      image: networknt/com.networknt.ob.parties-3.1.2:latest
      volumes:
        - ./parties:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    products:
      image: networknt/com.networknt.ob.products-3.1.2:latest
      volumes:
        - ./products:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    scheduled-payments:
      image: networknt/com.networknt.ob.scheduledpayments-3.1.2:latest
      volumes:
        - ./scheduled-payments:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    standing-orders:
      image: networknt/com.networknt.ob.standingorders-3.1.2:latest
      volumes:
        - ./standing-orders:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    statements:
      image: networknt/com.networknt.ob.statements-3.1.2:latest
      volumes:
        - ./statements:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    transactions:
      image: networknt/com.networknt.ob.transactions-3.1.2:latest
      volumes:
        - ./transactions:/config
      environment:
        - STATUS_HOST_IP=${DOCKER_HOST_IP}
      network_mode: host    
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-client"
      #    env: "dev"
