# Use this config file to overwrite values from other config files.
server.serviceId: com.networknt.ob.transactions-3.1.2
server.enableRegistry: true
server.dynamicPort: true
client.verifyHostname: false
openapi-security.enableVerifyJwt: true
openapi-validator.skipBodyValidation: true
